sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: hHDHLiIjJtO6XS64W+Kadss+t0UA4wsT3gTdnRL7W7PghiwV+EyUjKyLP+vKtd0OPmhXsoFVllKQYSjP4PUeuPrMBWYn/3+bdG6u1M6VWVCHs/WsDR8cCtmsT9EMNVbUaCSZ+cw5J6JdSAv2jSQT2ChCCHMOr9jJsORQDq4ZCz51GxMGqpGmDTF36h3XacJxkOc74e2ndeoss7UV8ugwqg68/6AL7/3k3/EHvwPmjBX2VppCHKiZ9hdnawlG48zYzcgZ1/DE1Qop59G5QtRsiBSdKOoEw1ODz94pZq64i0ao62o1Q8hh6aq6QtvJILbXI5QPVwMhYe8I+f5Uof8gQGASpn3/4zE6vwCrRls/FnScQZ1HmVOmu274yUAH45zcFhmI0Dei/a2Vzvi46+mHlOG3fqmx5tKqYhrFOkf+5/HYNq3WK4jKAmxw0Yc/3EV4IGq0AoaQuqZPDq5hbXUtfuaTpWj1QdRnlZ0icfDZ8sbQ9pqa2U4Qwpu+q1kI5Lc1UcUauy5kGXIHpd+T+eT7/oxWQYDBsFG0qb+CNieKUPzd/T9+HJWNtq4vSL3Kw3cyImgJ5yN/jvFDQegcia7VsUd9yBr1Aq9H66m8zBurLBWbN1tRe0R96KfZ4cjjmj87wM/FBOcHiofQ7U/htKrixWsRCmXBttvxHoqJXlSbKp8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Snow-Bound-at-Eagle-s_2297
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy